### ISSUE TITLE
저기 그럼 솔로랜드를 써야하는거죠?

### ISSUE THREAD

**Issue by shdudwns** [NLOGPlugins/NLOGConvert#1]
솔로랜드에서 땅을생성후 이플긴을 쓰면 변환되죠?
근데 솔로랜드 정상작동하는것이 있나요?

**Comment by shdudwns** [comment]
아..누킷맵이구나

**Comment by nnnlog** [comment]
@shdudwns 누킷에서 생성한 솔로랜드 월드를 PM의 심플에리어 월드 파일로 바꿔주는 역할을 합니다.

**Comment by shdudwns** [comment]
Land는 월드파일안에다 넣어요?

**Comment by nnnlog** [comment]
@shdudwns 개인용 플러그인이니까 안 쓰는거 추천합니다.
